### ISSUE TITLE
Add "use secondary only" option

### ISSUE THREAD

**Issue by igorandreoni** [growth-astro/growth-too-marshal#133]
Last night I wanted to trigger only on one secondary grid field, but it was very tricky (impossible?) to remove primary grid fields. Can we add a "use secondary only" option in the planning, as we have a "use primary only" option already?

**Comment by mcoughlin** [comment]
@igorandreoni Is this in the context of a skymap or in the Manual submission mode? Because a single secondary field should be done from the manual page. I committed not a --doUseSecondary option to gwemopt, and I am not opposed to adding a marshal button, but mostly wanted to understand the use case.

**Comment by igorandreoni** [comment]
I guess going for manual submission is the easiest way around this. Fine with me, I can close the issue. Thanks @mcoughlin
